from collections import defaultdict


def register_employee_face(user):
    images = capture_face_images()
    embedding = generate_face_embedding(images)
    save_employee_embedding(user, embedding)

def compute_result_data(result):
    if not result or "metadatas" not in result or "distances" not in result:
        print("Invalid result format:", result)
        return "No result is generated by the LLM model. Please check the logs for more details."
    employee_scores = defaultdict(list)

    for metadata, distance in zip(result["metadatas"], result["distances"]):
        emp = metadata[0]["employee_id"]
        employee_scores[emp].append(distance[0])

    print(employee_scores)
    avg_distance = {
        emp: sum(distances) / len(distances)
        for emp, distances in employee_scores.items()
    }
    small=100
    small_itr=0
    print(avg_distance)
    for it in avg_distance.keys():
        if avg_distance[it]<small:
            small=avg_distance[it]
            small_itr=it
    print(small_itr,small)
    score=1-small
    employee_id=small_itr
    return {
        "employee_id": employee_id,
        "score": score
    }

COSINE_DISTANCE_THRESHOLD = 0.45

def select_best_employee(
    metadatas: list[dict[str, any]],
    distances: list[float],
    threshold: float = COSINE_DISTANCE_THRESHOLD
) -> dict[str, any]:
    """
    Select the best employee from Chroma results.

    Chroma cosine distance:
        lower distance = better match

    The employee is accepted only when its distance
    is less than or equal to the configured threshold.
    """

    employee_distances = defaultdict(list)

    for metadata, distance in zip(metadatas, distances):
        if not metadata:
            continue

        employee_id = metadata.get("employee_id")

        if employee_id is None:
            continue

        employee_distances[str(employee_id)].append(float(distance))

    if not employee_distances:
        return {
            "employee_id": None,
            "distance": None,
            "similarity": None,
            "matched": False,
            "reason": "No employee metadata found"
        }

    # For each employee, use their closest enrolled face.
    best_distance_per_employee = {
        employee_id: min(employee_distances[employee_id])
        for employee_id in employee_distances
    }

    # Lower cosine distance is better.
    best_employee_id, best_distance = min(
        best_distance_per_employee.items(),
        key=lambda item: item[1]
    )

    similarity = 1.0 - best_distance

    if best_distance > threshold:
        return {
            "employee_id": None,
            "distance": best_distance,
            "similarity": similarity,
            "matched": False,
            "reason": "Best candidate did not pass the threshold"
        }

    return {
        "employee_id": best_employee_id,
        "distance": best_distance,
        "similarity": similarity,
        "matched": True,
        "reason": "Employee matched successfully"
    }